import Head from 'next/head'
import Image from 'next/image'
import ActiveSprint from '../components/activeSprintComponents/ActiveSprint';
import styles from '../styles/Home.module.scss'
import Homepage from './homepage';
// import 'font-awesome/css/font-awesome.min.css'
// import 'bootstrap/dist/css/bootstrap';

export default function Home() {
  return (
    // <div className={styles.container}>
    //   <Head>
    //     <title>Your work-Jira</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/jira-logo2.png" width="30px" />
    //   </Head>
    //   <main>
    //   <Homepage/>
    //   </main>
    //   <footer className={styles.footer}>
    //     I am Footer section
    //   </footer>
    // </div>
    <>
      <ActiveSprint/>
    </>
  )
  
}
