import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Homepage from './homepage';
// import 'font-awesome/css/font-awesome.min.css'
// import 'bootstrap/dist/css/bootstrap';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Your work-Jira</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/jira-logo2.png" width="30px" />
      </Head>
      {/* <i className="fa fa-spinner fa-spin"></i>
      <i className="fa fa-solid fa-grid"></i>
      <i className="fa-brands fa-react"></i> */}
      {/* <main className={styles.main}> */}
       <Homepage/>
      {/* </main> */}

      <footer className={styles.cutom_text_color}>
        I am Footer section
      </footer>
    </div>
  )
  
}
