// import Head from "next/head";
// import Image from "next/image";
// import Link from "next/link";
// import { useState } from "react";
// import { FiLock, FiUnlock, FiAtSign} from "react-icons/fi";
// import { FcGoogle } from "react-icons/fc";
// import { BsGithub } from "react-icons/bs";
// import { signIn } from "next-auth/react";

// export default function Login() {
//   const [show, setShow] = useState(false);

//   async function handleGoogleSignin(){
//     signIn("google", { callbackUrl: "https://jira-software.vercel.app" });
//   }

// //   async function handleGithubSignin(){
// //     signIn("github", { callbackUrl: "http://localhost:3000" });
// //   }

//   return (
//     <>
//       <Head>
//         <title>Next.js Authentication Example</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main>
//       <div className="px-5 pt-10 pb-5 flex m-auto justify-center align-middle place-items-center">
//           <div className="grid md:grid-cols-2 sm:grid-cols-1 grid-cols-1 justify-evenly w-[800px] h-[550px]">
//             <div className="lg:flex md:flex sm:hidden hidden bg-white rounded-bl-2xl rounded-tl-2xl">
//               <Image
//                 src="/login.jpg"
//                 className="lg:rounded-bl-2xl lg:rounded-tl-2xl select-none"
//                 alt="login"
//                 width={500}
//                 height={500}
//                 priority
//                 style={{ width: "100%", height: "100%" }}
//               />
//             </div>
//             <div className="bg-gray-50 lg:rounded-br-2xl lg:rounded-tr-2xl md:rounded-none rounded-2xl p-3 ">
//               <div className="-z-1 flex flex-col justify-center align-middle place-items-center">
//                 <h1 className="text-3xl font-extrabold mt-10 mb-2">Sign in</h1>
//                 <p className="text-center text-sm inputBox md:mb-10 sm:mb-8 mb-6 text-gray-700">
//                   Welcome back, Please enter your details.
//                 </p>

//                 <div className="flex inputBox relative justify-center align-middle">
//                   <input
//                     type="email"
//                     className="input_text w-full my-1 rounded-lg border p-3 pr-12 outline-none focus:border-indigo-400 transition-all"
//                     placeholder="Email"
//                   />
//                   <span className="flex text-gray-400 absolute self-center right-[2px] items-center p-3">
//                     <FiAtSign size={20} strokeWidth={1.5} />
//                   </span>
//                 </div>
//                 <div className="flex inputBox relative justify-center align-middle">
//                   <input
//                     type={show ? "text" : "password"}
//                     className="input_text w-full my-1 rounded-lg border p-3 pr-12 outline-none focus:border-indigo-400 transition-all"
//                     placeholder="Password"
//                   />
//                   <span
//                     className="flex text-gray-400 absolute self-center right-[2px] items-center p-3"
//                     onClick={() => setShow(!show)}
//                   >
//                     {show == false ? (
//                       <FiLock size={20} strokeWidth={1.5} className="cursor-pointer" />
//                     ) : (
//                       <FiUnlock size={20} strokeWidth={1.5} className="cursor-pointer" />
//                     )}
//                   </span>
//                 </div>
//                 <div className="flex inputBox">
//                   <button
//                     type="submit"
//                     className="w-full text-white my-4 rounded-lg bg-gradient-to-r from-indigo-500 to-blue-800  p-3 focus:outline-none active:scale-95 transition-transform"
//                   >
//                     Login
//                   </button>
//                 </div>
//                 <div className="flex inputBox">
//                   <button
//                     type="submit"
//                     onClick={handleGoogleSignin}
//                     className="text-sm w-full flex flex-row justify-between align-middle place-items-center py-3 px-4 border my-1 rounded-lg outline-none active:scale-95 transition-transform"
//                   >
//                     Sign in with Google<FcGoogle size={24} />
//                   </button>
//                 </div>
//                 <div className="flex inputBox">
//                   <button
//                     type="submit"
//                     // onClick={handleGithubSignin}
//                     className="text-sm w-full flex flex-row justify-between align-middle place-items-center py-3 px-4 border my-1 rounded-lg outline-none active:scale-95 transition-transform"
//                   >
//                     Sign in with Github<BsGithub size={24} />
//                   </button>
//                 </div>
//                 <div className="flex inputBox justify-center mt-5 md:mb-8 sm:mb-6 mb-5">
//                   <div className="text-sm text-center text-gray-600">
//                     Not registered yet?
//                     <Link href="/signup" className="text-blue-600">
//                       Create an account
//                     </Link>
//                   </div>
//                 </div>
//               </div>
//             </div>
//           </div>
//         </div>
//       </main>
//     </>
//   );
// }


import React from "react";
import { FcGoogle } from "react-icons/fc";
import {RiErrorWarningFill} from "react-icons/ri";
import Link from "next/link";
import { useFormik } from "formik";
import loginValidate from "../lib/validate";
import { signIn } from "next-auth/react";
import Image from "next/image";

const Login = () => {

  const formik = useFormik({
    initialValues:{
      email:""
    },
    validate:loginValidate,
    onSubmit
  });

  async function handleGoogleSignin(){
    signIn("google", { callbackUrl: "http://localhost:3000" });
  }

  async function onSubmit(values){
    console.log(values);
  }

  return (
    <>
      <div className="bg-[#FAFBFC] min-h-screen">
        <div className="container mx-auto py-8">
          <h1 className="text-[#0052CC] text-center font-bold text-4xl select-none">
            ATLASSIAN
          </h1>
          <div className="flex justify-center md:mt-12 sm:mt-8 mt-4">
            <form
              onSubmit={formik.handleSubmit}
              method="post"
              className="md:bg-white py-7 px-5 w-[400px] rounded-sm md:shadow-md flex flex-col place-items-center"
            >
              <div className="text-center">
                <p className="font-bold text-[#5E6C84]">
                  Log in to your account
                </p>
              </div>
              <div className="text-center mt-6 md:w-80 w-full">
                <input
                  type="email"
                  name="email"
                  placeholder="Enter email"
                  className={`w-full text-[#091E42] border-2 border-[#dfe1f6] ${formik.errors.email ? "border-[#BB4B3D] focus:border-[#BB4B3D]" : ""} p-2 rounded outline-none focus:border-[#528cd6] transition-colors ease-in-out bg-[#fafbfc] hover:bg-[#ebebeb] focus:bg-white`}
                  // onChange={formik.handleChange}
                  // value={formik.values.email}
                  {...formik.getFieldProps("email")}
                />

                {
                  formik.errors.email && formik.touched.email ? (<p className="absolute flex text-[#BB4B3D] text-sm gap-x-1  align-middle place-items-center">
                  <RiErrorWarningFill />
                  {formik.errors.email}
                </p>) : null

                }
                
              </div>
              <div className="text-center mt-6 md:w-80 w-full">
                <button
                  type="submit"
                  className="w-full p-2 bg-[#0052CC] font-medium text-white rounded hover:bg-[#196be6] active:bg-[#154da1]"
                >
                  Continue
                </button>
              </div>
              <div className="text-center my-3 select-none  md:w-80 w-full">
                <p className="text-[14px] text-[#97A0AF]">OR</p>
              </div>
              <div className="text-center my-3 md:w-80 w-full">
                <button
                  type="button"
                  onClick={handleGoogleSignin}
                  className="w-full flex flex-row justify-around text-center place-items-center p-2 bg-white font-medium drop-shadow-md rounded hover:bg-[#FAFBFC] text-[#42526E]"
                >
                  <FcGoogle size={20} className="" />
                  Continue with Google
                </button>
              </div>
              <div className="text-center my-3 md:w-80 w-full">
                <button
                  type="button"
                  className="w-full flex flex-row justify-around text-center place-items-center p-2 bg-white font-medium drop-shadow-md rounded hover:bg-[#FAFBFC] text-[#42526E]"
                >
                  <Image width={18} height={18} src="/microsoft-logo.svg" className="" />
                  Continue with Microsoft
                </button>
              </div>
              <div className="text-center my-3 md:w-80 w-full">
                <button
                  type="button"
                  className="w-full flex flex-row justify-around text-center place-items-center p-2 bg-white font-medium drop-shadow-md rounded hover:bg-[#FAFBFC] text-[#42526E]"
                >
                  <Image width={18} height={18} src="/apple-logo.svg" className="" />
                  Continue with Apple
                </button>
              </div>
              <div className="text-center my-3 md:w-80 w-full">
                <button
                  type="button"
                  className="w-full flex flex-row justify-around text-center place-items-center p-2 bg-white font-medium drop-shadow-md rounded hover:bg-[#FAFBFC] text-[#42526E]"
                >
                  <Image width={18} height={18}
                    src="/slack-logo.svg"
                    className="w-[18px] h-[18px]"
                  />
                  Continue with Slack
                </button>
              </div>
              <hr className="border-1 border-[#D5D8DE] md:w-80 w-full mt-6 mb-1" />
              <div className="flex justify-center gap-x-3 text-center my-3 md:w-80 w-full">
                <Link href={"#"} className="text-[#0052CC] hover:underline">
                  Can&apos;t log in?
                </Link>
                <p className="text-gray-500">&#8226;</p>
                <Link href={"#"} className="text-[#0052CC] hover:underline">
                  Sign up for an account
                </Link>
              </div>
            </form>
          </div>
          <div className="flex justify-center gap-x-3 text-center mt-3 mb-4 w-full">
            <Link href={"#"} className="text-[#0052CC] hover:underline text-sm">
              Privacy Policy
            </Link>
            <p className="text-gray-500">&#8226;</p>
            <Link href={"#"} className="text-[#0052CC] hover:underline text-sm">
              User Notice
            </Link>
          </div>
          <h1 className="text-[#42526E] text-center font-bold text-3xl select-none">
            ATLASSIAN
          </h1>
        </div>
      </div>
    </>
  );
};

export default Login;