import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { FiLock, FiUnlock, FiAtSign} from "react-icons/fi";
import { FcGoogle } from "react-icons/fc";
import { BsGithub } from "react-icons/bs";
import { signIn } from "next-auth/react";

export default function Login() {
  const [show, setShow] = useState(false);

  async function handleGoogleSignin(){
    signIn("google", { callbackUrl: "https://jira-software.vercel.app" });
  }

//   async function handleGithubSignin(){
//     signIn("github", { callbackUrl: "http://localhost:3000" });
//   }

  return (
    <>
      <Head>
        <title>Next.js Authentication Example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div className="px-5 pt-10 pb-5 flex m-auto justify-center align-middle place-items-center">
          <div className="grid md:grid-cols-2 sm:grid-cols-1 grid-cols-1 justify-evenly w-[800px] h-[550px]">
            <div className="lg:flex md:flex sm:hidden hidden bg-white rounded-bl-2xl rounded-tl-2xl">
              <Image
                src="/login.jpg"
                className="lg:rounded-bl-2xl lg:rounded-tl-2xl select-none"
                alt="login"
                width={500}
                height={500}
                priority
                style={{ width: "100%", height: "100%" }}
              />
            </div>
            <div className="bg-gray-50 lg:rounded-br-2xl lg:rounded-tr-2xl md:rounded-none rounded-2xl p-3 ">
              <div className="-z-1 flex flex-col justify-center align-middle place-items-center">
                <h1 className="text-3xl font-extrabold mt-10 mb-2">Sign in</h1>
                <p className="text-center text-sm inputBox md:mb-10 sm:mb-8 mb-6 text-gray-700">
                  Welcome back, Please enter your details.
                </p>

                <div className="flex inputBox relative justify-center align-middle">
                  <input
                    type="email"
                    className="input_text w-full my-1 rounded-lg border p-3 pr-12 outline-none focus:border-indigo-400 transition-all"
                    placeholder="Email"
                  />
                  <span className="flex text-gray-400 absolute self-center right-[2px] items-center p-3">
                    <FiAtSign size={20} strokeWidth={1.5} />
                  </span>
                </div>
                <div className="flex inputBox relative justify-center align-middle">
                  <input
                    type={show ? "text" : "password"}
                    className="input_text w-full my-1 rounded-lg border p-3 pr-12 outline-none focus:border-indigo-400 transition-all"
                    placeholder="Password"
                  />
                  <span
                    className="flex text-gray-400 absolute self-center right-[2px] items-center p-3"
                    onClick={() => setShow(!show)}
                  >
                    {show == false ? (
                      <FiLock size={20} strokeWidth={1.5} className="cursor-pointer" />
                    ) : (
                      <FiUnlock size={20} strokeWidth={1.5} className="cursor-pointer" />
                    )}
                  </span>
                </div>
                <div className="flex inputBox">
                  <button
                    type="submit"
                    className="w-full text-white my-4 rounded-lg bg-gradient-to-r from-indigo-500 to-blue-800  p-3 focus:outline-none active:scale-95 transition-transform"
                  >
                    Login
                  </button>
                </div>
                <div className="flex inputBox">
                  <button
                    type="submit"
                    onClick={handleGoogleSignin}
                    className="text-sm w-full flex flex-row justify-between align-middle place-items-center py-3 px-4 border my-1 rounded-lg outline-none active:scale-95 transition-transform"
                  >
                    Sign in with Google<FcGoogle size={24} />
                  </button>
                </div>
                <div className="flex inputBox">
                  <button
                    type="submit"
                    // onClick={handleGithubSignin}
                    className="text-sm w-full flex flex-row justify-between align-middle place-items-center py-3 px-4 border my-1 rounded-lg outline-none active:scale-95 transition-transform"
                  >
                    Sign in with Github<BsGithub size={24} />
                  </button>
                </div>
                <div className="flex inputBox justify-center mt-5 md:mb-8 sm:mb-6 mb-5">
                  <div className="text-sm text-center text-gray-600">
                    Not registered yet?
                    <Link href="/signup" className="text-blue-600">
                      Create an account
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}